<font size=6>**TD 1 : de la chaîne de caractères au sac de mots**</font>

Julien Velcin, Université Lyon 2 - Master Humanités Numériques

Ce TD utilise une partie du tutoriel donné par A. Gramfort et A. Mueller à SciPy 2017
https://github.com/amueller/scipy-2017-sklearn ainsi qu'un article du blog de Thomas Buhrmann https://buhrmann.github.io/tfidf-analysis.html

Il est utilisé dans des travaux pratiques en complément d'un cours magistral qui explique les notions fondamentales de du traitement des données textuelles.

# Differentes manières de représenter des données textuelles

- Chaîne de caractères (string)
- Bag-of-Words (BoW)
- Vector Space Model (VSM)
- Ajouter des méta-données (par ex. catégories grammaticales)
- Représentations plus complexes : arbres syntaxiques, graphes, etc.

Chaque représentation implique une manière différente de *comparer* les documents.

## Un exemple très simple

*"John Doe has bought an apple."*

Point de vue linguistique:

<table style="border:0;">
<tr style="border:0;">
<td style="border:0; white-space:pre; padding:0 100px 0 0px;">"John Doe has bought an apple."</td>
<td style="border:0;"><img src="img/syntaxtree.png" style='height: 150px'/></td>
</tr>
</table>

Point de vue statistique :

<img src="img/bow-illu.png" style='height: 150px'/>

<table style="border:0;">
<tr style="border:0;">
<td style="border:0; white-space:pre; padding:0 100px 0 0px;">"John Doe has bought an apple."</td>
<td style="border:0;">{ apple,<br/><br/> bought,<br/><br/>John_Doe } </td>
</tr>
</table>

## Vers l'espace vectoriel

<img src="img/bow.png" style='height: 400px'/>

On peut déjà observer des problèmes évidents, tel que :

*"Mary asked Fred out."*
<br/>
*"Fred asked Mary out."*

La représentation est la même :
<img src="img/mary.png" style='height: 200px'/>

A partir d'un *ensemble* de documents, on souhaite obtenir l'objet suivant :
<img src="img/termdocmatrix.png" style='height: 300px'/>

Par exemple :
<img src="img/termdocmatrix-2.jpg" style='width: 400px'/>

# Extraire les caractéristiques des textes

En pratique, on utilise le formalisme du "sac de mots" et on suit plusieurs étapes :

<img src="img/bag_of_words.svg" width="100%">


Prenons à présent deux documents, tels que :

In [1]:
X = ["Some say the world will end in fire,",
     "Some say in ice."]

In [2]:
len(X)

2

La librairie contient une fonction qui permet de "vectoriser" un ensemble de textes en prenant en compte un certain nombre de prétraitements (*preprocessing*) couramment employés : mis en minuscule, utilisation de mots-outils, etc.

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorizer.fit(X)

CountVectorizer()

In [100]:
#help(CountVectorizer)

Observons le vocabulaire automatiquement construit à partir de ces deux textes :

In [5]:
vectorizer.vocabulary_

{'some': 5,
 'say': 4,
 'the': 6,
 'world': 8,
 'will': 7,
 'end': 0,
 'in': 3,
 'fire': 1,
 'ice': 2}

Quelques mots sur la présence de mots tels que "in" ou "the"

Mots les plus fréquents observés dans Harry Potter :

<img src="img/zipf_1.png" width="100%">

Cette forme particulière est appelée "loi de Zipf". Elle a été observée pour la première fois par le linguiste George K. Zipf (1902-1950).

La loi de Zipf indique que si l'on observe un corpus suffisamment grand, la fréquence d'apparition d'un mot est **inversement proportionnelle** à son rang dans la table des fréquences.

Même graphique mais en supprimant les mots-outils anglais :
    
<img src="img/zipf_2.png" width="100%">

D'autres prétraitements sont également disponibles, tels que :

* racinisation (stemming) : trouver la racine des mots, comme dans :
     
> learn: learns, learned, learning...<br/>
> march: marcher, marchera, marcherai...
 
* lemmatisation (lemmatization) : trouver le lemme, comme dans :

> to be: am, are<br/>
> être : suis, sont...  

Le stemming nous aide à :

- rapprocher deux documents sémantiquement liés mais n'utilisant pas exactement les mêmes termes
- réduire la taille du vocabulaire (cf. malédiction de la dimension)

Ok pour :

    adventur: [adventure,adventurer,adventurers,adventures,adventurous]

mais...

    anim: [animal, animals, animation]



En pratique, la **lemmatisation** peut être réalisée via des librairies comme *spacy* ou *stenza* (cf. cours précédent).

Le **stemming** peut être réalisé en amont avec des librairies comme *nltk*, par exemple :

In [6]:
from nltk.stem.snowball import SnowballStemmer

# on commence par créer un nouvel "analyseur" utilisant le stemming (dans la bonne langue)

#stemmer_fr = SnowballStemmer("french")
stemmer_en = SnowballStemmer("english") # à priori, il s'agit ici de l'algorithme de Porter

analyzer_with_stemming = CountVectorizer().build_analyzer()

def stemmed_words_en(doc):
    return (stemmer_en.stem(w) for w in analyzer_with_stemming(doc))

# à présent, on initialisale le "vectorize" avec le nouvel analyseur basé sur le stemming :
stem_vectorizer_en = CountVectorizer(analyzer=stemmed_words_en)

# le reste est identique : construction du vocabulaire (fit) puis de la matrice (transform) :
stem_vectorizer_en.fit(X)
stem_vectorizer_en.transform(X)

<2x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

Autre prétraitement utile : pouvoir **remplacer** certains motifs trouvés dans les textes

In [7]:
print(X)
str = [x.replace("world", "worlds") for x in X]
print(str)

['Some say the world will end in fire,', 'Some say in ice.']
['Some say the worlds will end in fire,', 'Some say in ice.']


In [8]:
import re
re.sub("[s|S]+\w*", "truc", X[0])

'truc truc the world will end in fire,'

Corriger automatiquement l'orthographe des mots grâce à la distance d'édition (ou distance Levenshtein, proposée en 1965).
Il s'agit de calculer le plus petit nombre d'opérations (insertion, suppression, remplacement) pour passer d'une chaîne à une autre.

In [9]:
# one possible implementation from https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#Python
def levenshtein(s1, s2):
    if len(s1) < len(s2):
        return levenshtein(s2, s1)

    # len(s1) >= len(s2)
    if len(s2) == 0:
        return len(s1)

    previous_row = range(len(s2) + 1)
    for i, c1 in enumerate(s1):
        current_row = [i + 1]
        for j, c2 in enumerate(s2):
            insertions = previous_row[j + 1] + 1 # j+1 instead of j since previous_row and current_row are one character longer
            deletions = current_row[j] + 1       # than s2
            substitutions = previous_row[j] + (c1 != c2)
            current_row.append(min(insertions, deletions, substitutions))
        previous_row = current_row
    
    return previous_row[-1]

In [10]:
#levenshtein("chaîne", "chaine")
#levenshtein("chaîne", "chiane")
levenshtein("remerciement", "remerciments")

2

# Matrice documents x termes

## Codage TF

On peut maintenant construire la matrice documents * termes :

In [11]:
X_bag_of_words = vectorizer.transform(X)

In [12]:
X_bag_of_words.shape

(2, 9)

In [13]:
X_bag_of_words

<2x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

Jetons un oeil au contenu de la matrice :

In [14]:
X_bag_of_words.toarray()

array([[1, 1, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 0, 0]])

In [15]:
# exemple avec un second corpus

#X = ["Some say the world will end in fire,",
#     "Some say in ice."]
#X_2 = ["Some world say will end in : fire the with new words !,",
#     "Some in ice say."]
X_2 = ["Some world say will end in : fire the with new words end!,",
     "Some in ice say ice ice."]
X_2_bag_of_words = vectorizer.transform(X_2)
X_2_bag_of_words.toarray()

array([[2, 1, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 3, 1, 1, 1, 0, 0, 0]])

In [16]:
# Le code ci-dessous si on souhaite utiliser un *nouveau* vectorizer (ie nouveau vocabulaire)

#X_2 = ["Some world say will end in : fire the with new words !,",
#     "Some in ice say."]
#vectorizer_2 = CountVectorizer()
#vectorizer_2.fit(X_2)
#X_2_bag_of_words = vectorizer_2.transform(X_2)
#X_2_bag_of_words.toarray()

On observe que la valeur indiquée dans une cellule est le nombre d'occurrences d'un terme dans un document (TF pour *Term Frequency*)

On peut également retrouver le nom des termes du vocabulaire :

In [17]:
vectorizer.get_feature_names_out()

array(['end', 'fire', 'ice', 'in', 'say', 'some', 'the', 'will', 'world'],
      dtype=object)

On peut retrouver les attributs (features) utilisés dans les documents :

In [18]:
vectorizer.inverse_transform(X_bag_of_words)

[array(['end', 'fire', 'in', 'say', 'some', 'the', 'will', 'world'],
       dtype='<U5'),
 array(['ice', 'in', 'say', 'some'], dtype='<U5')]

## Représentation TFxIDF
A la place du nombre d'occurrences (TF), on peut utiliser une autre mesure qui prend en compte la rareté d'un mot dans le corpus :

$$ tf_{t,d} \times idf_{t} $$

avec $tf_{t,d}$ le nombre d'occurrences de $t$ dans $d$

et $idf_{t} = \log \frac{N}{df_t}$ ($N$ est le nombre total de documents)

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit(X)

TfidfVectorizer()

In [20]:
import numpy as np
np.set_printoptions(precision=2)

X_TFxIDF = tfidf_vectorizer.transform(X)
print(X_TFxIDF.toarray())

[[0.39 0.39 0.   0.28 0.28 0.28 0.39 0.39 0.39]
 [0.   0.   0.63 0.45 0.45 0.45 0.   0.   0.  ]]


# Comparaison de deux textes

Les distances usuelles (ex. euclidenne) ne sont pas adaptées.

Dans les espaces à **beaucoup de dimensions** :

Pourquoi les banquiers n'ont jamais de lingots sphériques ?

Pourquoi les marchands d'oranges occupent beaucoup de place pour empiler peu d'oranges ?

http://www.brouty.fr/Maths/sphere.html (see "Curiosités du calcul")

Malédiction de la dimension (curse of dimensionality)

Richard E. Bellman (1920-1984): les hypervolumes sont presque vides!

<img src="img/curse.png" style='height: 400px'/>

Un volume avec $dim=d$ a besoin de $10^d$ données pour peupler équitablement l'espace.

## Produit scalaire et cosinus

$\vec{x}$ et $\vec{y}$ sont deux vecteurs dans le VSM.

Cosine est une mesure de **similarité** calculée sur l'angle formé par les deux vecteurs :

$$cos(\vec{x},\vec{y}) = \frac{\vec{x}.\vec{y}}{||\vec{x}||_2 \times ||\vec{y}||_2}$$

Elle prend une valeur entre 0 (rien en commun) et 1 (même vecteurs à une constante près).

## Interprétation géométrique

<img src="img/cosine.png" style='height: 300px'/>

## Exemple : distribution des mots les plus fréquents dans Harry Potter

Commençons par lire les données :

In [106]:
import os

with open(os.path.join("data", "Harry_Potter_1.txt")) as f:
    lines = [line.strip() for line in f.readlines()]

# version de base :
tf_vectorizer = CountVectorizer()

# version avec une liste de mots outils fournie
sw = ["they", "were", "to", "and"] # etc. (il est préférable de charger une liste depuis un fichier)
tf_vectorizer = CountVectorizer(stop_words=sw)
# si vous voulez utiliser une liste pré-construite :
#tf_vectorizer = CountVectorizer(stop_words="english")
# si vous voulez utiliser l'encodage TFxIDF :
#tfidf_vectorizer = TfidfVectorizer()

tf_vectorizer.fit(lines)

# montrer l'intégralité du vocabulaire (peut être long) :
#tf_vectorizer.vocabulary_

# si on veut tester le stemming (cf. point précédent) :
#stem_vectorizer_en = CountVectorizer(analyzer=stemmed_words_en)
#stem_vectorizer_en.fit(lines)

CountVectorizer(stop_words='english')

In [107]:
X_hp = tf_vectorizer.transform(lines)
features_hp = tf_vectorizer.get_feature_names_out()
#len(features_hp)
#features_hp[0:10]

On peut utiliser quelques fonctions pour afficher le vecteur pour un document en particulier :

In [108]:
import pandas as pd

# des options permettent de limiter (ou non) le nombre de lignes/colonnes affichées
# par exemple :
# pd.set_option('display.max_rows', None)

def top_feats(row, features, top_n=25):
    ''' Get top n tfidf values in row and return them with their corresponding feature names.'''
    topn_ids = np.argsort(row)[::-1][:top_n]
    top_feats = [(features[i], row[i]) for i in topn_ids if row[i]>0]
    df = pd.DataFrame(top_feats)
    if len(top_feats) > 0:
        df.columns = ['feature', 'score']
    return df

def top_feats_in_doc(Xtr, features, row_id, top_n=25):
    ''' Top features in specific document (matrix row) '''
    row = np.squeeze(Xtr[row_id].toarray())
    return top_feats(row, features, top_n)


In [105]:
print(lines[4])
top_feats_in_doc(X_hp, features_hp, 4, top_n=30)

#print(lines[6])
#top_feats_in_doc(X_hp, features_hp, 6, top_n=50)

Mr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much. They were the last people you’d expect to be involved in anything strange or mysterious, because they just didn’t hold with such nonsense.


feature  score
0          you      2
1       people      1
2         very      1
3         much      1
4      dursley      1
5           mr      1
6      because      1
7          say      1
8         didn      1
9      strange      1
10       proud      1
11         the      1
12    involved      1
13        last      1
14    anything      1
15      number      1
16          of      1
17        four      1
18        hold      1
19        just      1
20  mysterious      1
21         mrs      1
22        that      1
23   perfectly      1
24      privet      1
25        with      1
26      expect      1
27          or      1
28    nonsense      1
29          in      1

Afficher les mots les plus fréquents :

In [26]:
D = X_hp.toarray()

n_docs, n_terms = D.shape

#tf_means = np.mean(D, axis=0)
tf_sum = np.sum(D, axis=0)
top_feats(tf_sum, features_hp)

feature  score
0      the   3627
1      and   1923
2       to   1861
3       he   1759
4    harry   1326
5       of   1267
6       it   1186
7      was   1186
8      you   1037
9       in    967
10     his    937
11    said    794
12     had    701
13    they    691
14    that    688
15      on    637
16      at    625
17      as    526
18     him    501
19     but    485
20     ron    429
21    with    416
22     all    397
23    what    386
24     out    375

Comparer des documents revient à comparer les valeurs de deux colonnes (vecteurs).

In [53]:
import math

# fonction calculant le cosinus entre deux vecteurs
def cosinus(i, j):
    num = np.dot(i, j)
    den = math.sqrt(sum(i*i))*math.sqrt(sum(j*j))
    if (den>0):    
        return (num/den)
    else:
        return 0

In [45]:
print(top_feats_in_doc(X_hp, features_hp, 5, top_n=40))
print(top_feats_in_doc(X_hp, features_hp, 10, top_n=40))

      feature  score
0         the      4
1         was      4
2         and      3
3          of      3
4          he      2
5        very      2
6     dursley      2
7          in      2
8       which      2
9      called      2
10        had      2
11       neck      2
12       thin      1
13         mr      1
14     garden      1
15        man      1
16      their      1
17      beefy      1
18        big      1
19   director      1
20   anywhere      1
21       have      1
22      there      1
23       came      1
24      twice      1
25       made      1
26       much      1
27        mrs      1
28       firm      1
29         on      1
30  neighbors      1
31        did      1
32        she      1
33      small      1
34      spent      1
35  grunnings      1
36       over      1
37      usual      1
38         as      1
39    craning      1
     feature  score
0         he      2
1        got      1
2       tyke      1
3         mr      1
4       four      1
5       left      1

In [58]:
cosinus(D[5, :], D[10, :])
#cosinus(D[2, :], D[5, :])
#cosinus(D[2, :], D[0, :])
#cosinus(D[2, :], D[2, :])

0.31859654643215496

# Créer son propre moteur de recherche

In [30]:
#features_hp[0:10]

In [89]:
#query = ['privet', 'drive', 'dursley']
#query = ['privet', 'privet', 'drive', 'dursley']
query = ['chess', 'chess', 'chess', 'harry', 'play']
#query = ['1473', 'aaaaarrrgh']

indexes = [np.where(features_hp == q)[0][0] for q in query if q in features_hp]
print(indexes)

[818, 818, 818, 2246, 3543]


On construit un vecteur de la même taille que le vocabulaire. Il est initialisé à zéro, puis on y met la valeur 1 pour les termes de la requête.

In [90]:
query_vec = np.zeros(n_terms)

#query_vec[indexes] = 1

for tt in indexes:
    query_vec[tt] += 1

In [91]:
#len(query_vec)
query_vec[3658:3670]
#query_vec[810:830]
#query_vec[0:10]
#query_vec[1410:1420]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

On peut vérifier que le vecteur requête contient bien 3 éléments non nuls.

In [92]:
sum(query_vec)

5.0

Calcul du cosinus vis-à-vis de la requête pour 1 document :

In [93]:
cosinus(D[5, :], query_vec)

0.0

On automatise en calculant pour tous les docs et on triant le résultat :

In [94]:
# fonction qui crée un dictionnaire associant le cosinus à chaque document
# puis le trie de manière décroissante

def search(q, D):
    cc = {i: cosinus(D[i, :], q) for i in range(n_docs)}
    cc = sorted(cc.items(), key=lambda x: x[1], reverse=True)
    return cc

In [95]:
result = search(query_vec, D)

In [96]:
result[0:10]

[(2137, 0.5698028822981898),
 (3135, 0.30151134457776363),
 (1060, 0.2461829819586655),
 (2896, 0.24174688920761409),
 (2192, 0.24120907566221092),
 (2890, 0.23652495839563303),
 (3179, 0.21320071635561047),
 (129, 0.21320071635561041),
 (815, 0.21320071635561041),
 (942, 0.21320071635561041)]

On ne retient que les dix premiers résultats (par exemple).

In [97]:
nb_top_docs = 10
top_docs = [r for (r,v) in result[0:nb_top_docs]]
print(top_docs)

[2137, 3135, 1060, 2896, 2192, 2890, 3179, 129, 815, 942]


Pour finir, on peut afficher les textes les plus pertinents pour la requête :

In [98]:
for i, td in zip(range(nb_top_docs), top_docs):
    #print(top_feats_in_doc(X_hp, features_hp, td))
    print("%s (%s): %s" % (i+1, td, lines[td]))

1 (2137): “Want to play chess, Harry?” said Ron.
2 (3135): “Harry!”
3 (1060): “Harry Potter,” said Harry.
4 (2896): “White always plays first in chess,” said Ron, peering across the board. “Yes...look...”
5 (2192): The rest of the team hung back to talk to one another as usual at the end of practice, but Harry headed straight back to the Gryffindor common room, where he found Ron and Hermione playing chess. Chess was the only thing Hermione ever lost at, something Harry and Ron thought was very good for her.
6 (2890): Harry and Hermione stayed quiet, watching Ron think. Finally he said, “Now, don’t be offended or anything, but neither of you are that good at chess —”
7 (3179): “...for the best-played game of chess Hogwarts has seen in many years, I award Gryffindor house fifty points.”
8 (129): Harry groaned.
9 (815): Harry swallowed.
10 (942): “Harry Potter!”
